#!/usr/bin/env zsh

alias cm=chezmoi
alias cdz="cd ~/Work/src/zenvironment"
alias glances="glances --theme-white"

alias cma="cm apply"                        # ChezMoi Apply
alias cmd="cm diff"                         # ChezMoi Diff
alias cme="cm edit"                         # ChezMoi Edit
alias cmezrc="cm edit ~/.zshrc"             # ChezMoi Edit ZshRc
alias cmea="cm edit ~/.zshrc.d/10-aliases"  # ChezMoi Edit Aliases
