#!/usr/bin/env zsh

alias cdz="cd ~/Work/src/zenvironment"

# Actions
alias update-global-deps-brew="brew bundle --global"
alias update-global-deps-npm="npm update -g"
alias update-global-deps="update-global-deps-npm; update-global-deps-brew"

# Binary specific
alias glances="glances --theme-white"

alias cm=chezmoi
alias cma="cm apply"                        # ChezMoi Apply
alias cmd="cm diff"                         # ChezMoi Diff
alias cme="cm edit"                         # ChezMoi Edit
alias cmezrc="cm edit ~/.zshrc"             # ChezMoi Edit ZshRc
alias cmea="cm edit ~/.zshrc.d/10-aliases"  # ChezMoi Edit Aliases
