#!/usr/bin/env zsh
#
# misc options
#
setopt INTERACTIVE_COMMENTS  # Enable comments in interactive shell.

# Long running processes should return time after they complete. Specified
# in seconds.
REPORTTIME=2
TIMEFMT="%U user %S system %P cpu %*Es total"

# disable oh-my-zsh's auto-update in favor of zgen
DISABLE_AUTO_UPDATE=true
DISABLE_UNTRACKED_FILES_DIRTY="true"