#!/usr/bin/env zsh

# setup powerlevel10k prompt
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Valid font modes:
#   flat, awesome-patched, awesome-fontconfig, nerdfont-complete, nerdfont-fontconfig
export POWERLEVEL9K_MODE="nerdfont-fontconfig"

# Uncomment following line if you want red dots to be displayed while waiting for completion
export COMPLETION_WAITING_DOTS="true"

# Global ZSH settings
CASE_SENSITIVE="true"

# Create and load from the ~/.zshrc.d directory
mkdir -p ~/.zshrc.d
for file in ~/.zshrc.d/*; do
  source $file
done

# Load iTerm shell integrations if found.
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# To customize your prompt, run `p10k configure` or edit ~/.p10k.zsh.
if [[ ! -f ~/.p10k.zsh ]]; then
  echo "Run p10k configure or edit ~/.p10k.zsh to configure your prompt"
else
  source ~/.p10k.zsh
fi

# Added by Krypton
export GPG_TTY=$(tty)
