# base tools
brew "zsh"                          # `zsh`                     - if Jason Bourne went to MIT (bourne shell joke)
brew "bash"                         # `bash`                    - because Apply daddy won't fight GPLv3
