# identity tools
tap "str4d.xyz/rage", "https://str4d.xyz/rage"
brew "gnupg"                        # `gpg`                     - bob and alice are up to no good.. or are they?
brew "gpg2"                         # `gpg2`                    - bob and alice but a little newer
brew "age"                          # `age`                     - file encryption
brew "rage"                         # `rage`                    - like `age` but rust
brew "sops"                         # `sops`                    - secrets encrypted at rest
